services:

  wordpress:
    container_name: givelocalguide-blocksy-web
    image: wordpress:php8.3-apache
    platform: linux/arm64
    ports:
      - "8068:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_ENVIRONMENT_TYPE: local
    volumes:
      - ./:/var/www/html:delegated
      - ./volumes/shared:/mnt/shared
      - ./docker/php-custom.ini:/usr/local/etc/php/conf.d/zzz-upload.ini
    networks:
      - givelocalguide-blocksy-network

  db:
    container_name: givelocalguide-blocksy-db
    image: mysql:8.4
    platform: linux/arm64
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./volumes/mysql:/var/lib/mysql:delegated
      - ./volumes/shared:/mnt/shared:delegated
    networks:
      - givelocalguide-blocksy-network

  phpmyadmin:
    container_name: givelocalguide-blocksy-phpmyadmin
    image: arm64v8/phpmyadmin
    ports:
      - 8680:80
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 100M
    networks:
      - givelocalguide-blocksy-network

volumes:
  wordpress:
  db:

networks:
  givelocalguide-blocksy-network:
