services:

  nginx:
    image: nginx:1.25-alpine
    platform: linux/arm64
    ports:
      - "8068:443"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=443
    volumes:
      - ./:/var/www/html:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - wordpress
    networks:
      - givelocalguide-blocksy-network
    command: sh -c "nginx -g 'daemon off;'"

  wordpress:
    container_name: givelocalguide-blocksy-web
    image: wordpress:php8.2-fpm
    platform: linux/arm64
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_ENVIRONMENT_TYPE: local
    volumes:
      - ./:/var/www/html:delegated
      - ./volumes/shared:/mnt/shared
    networks:
      - givelocalguide-blocksy-network

  db:
    container_name: givelocalguide-blocksy-db
    image: mariadb:10.3
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./volumes/mysql:/var/lib/mysql:delegated
      - ./volumes/shared:/mnt/shared:delegated
    networks:
      - givelocalguide-blocksy-network

  phpmyadmin:
    container_name: givelocalguide-blocksy-phpmyadmin
    image: arm64v8/phpmyadmin
    ports:
      - 8680:80
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 100M
    networks:
      - givelocalguide-blocksy-network

volumes:
  wordpress:
  db:

networks:
  givelocalguide-blocksy-network:
